### ISSUE TITLE
Question about BankStander

### ISSUE THREAD

**Issue by Gimpy666** [ineedbots/srl-osr-scripts#1]
Hey @ineedbots 

Question about the BankStander - do you have any documentation as to what features are available in this script and how to configure it? I see there's a pile of stuff that it does, just wasn't sure how to go about setting a config and testing it out.

Thanks and awesome scripts, very well written and love that they're modular/object in design; very easy to use it as a framework for other types of scripts.

**Comment by ineedbots** [comment]
BANK_COLOR_TYPE :  choose the color of the bank the script will look for, can use NONE if using fixed RSW map coords (below)
GAINING_XP: are we gaining xp? (creating unf potions we dont)

MAP: which RSW map .png to use (for below)
BANK_LOCATIONS: locations of RSW map coords for the banks, use -1, to only use color

CREATION_TYPE: many options...
  TRANSFORM:  using a tool on material to create products, like knife -> logs, chisel -> amethyst
  COMBINE: using materials and a secondary material, combine items like herb -> water vial, jug of water -> grapes
  CLEANER: cleans herbs
  ENCHANTER: casts a spell on each of the materials, make sure to setup the correct spell in the config, use runes as the 'tools', like lvl1 enchant -> sapphire ring, superheat -> ore
  GLASSMAKE: casts glass make, make sure to have giant seaweed or seaweed set as the material, bucket of sand as the secondary, also works for degriming and humidify
  SUPERCOMBAT: supercombat

AMULET_OF_CHEM: are you using amulet of chem?

MAKE_NUM: which make index to select when it opens, like when using knife->log, select arrowshafts, shortbow, longbow, stock, etc.
SPELL_TO_CAST: which spell to cast for glassmake and enchanter creation types

TOOLS: tools, will not be banked, maybe used on material for transform creation type

MATERIALS: materials used in the creation process
MATERIAL_RATIO: how many materials does it take to create 1 product?

SECONDARY_MATERIALS: secondary materials used in the creation process, set to empty array if there are none
SECONDARY_MATERIAL_RATIO: how many secondary materials does it take to create 1 product?

PRODUCTS: what is the product of the creation process?

**Comment by Gimpy666** [comment]
Thanks for the documentation! This script is very customizable and powerful, going to have to give it a try.
