### ISSUE TITLE
EdgevilleSmelter - Mould Item Issues

### ISSUE THREAD

**Issue by heebybeeby** [ineedbots/srl-osr-scripts#3]
Whether I'm looking to make Cannonballs or jewelry, the script fails one way or another. 

When Cannonballs configured in config (this is configured on download), the script will withdraw iron bars instead of Steel despite steel being highlighted. 

When Jewelry is configured in config (mould is added, secondary is added, product is added, box coords are entered), script will walk to furnace and stall out.

Can you give a play by play on whats expected or is this just breaking at the moment?

**Comment by ineedbots** [comment]
are you sure that https://github.com/ineedbots/srl-osr-scripts/blob/master/EdgevilleSmelter/Config.simba is setup correctly? specifically the `MAKE_INTERFACE_BOX` and MAKE_INTERFACE`?

**Comment by heebybeeby** [comment]
MAKE_INTERFACE is True since there is a crafting interface. 
MAKE_INTERFACE_BOX is [277, 400, 295, 412], which is the top left and bottom right points on a box around the Ruby Bracelet in the crafting interface. Screen coords were grabbed using ACA.

**Comment by heebybeeby** [comment]
As for the default, which is cannonballs, it does not work "straight out of the box". Unsure if that is intentional or not. But the default values plugged in wont even make it to the furnace as it grabs Iron bars instead of Steel

**Comment by ineedbots** [comment]
As for cannonballs, the iron bars are prob false positiving with the steel bars. The itemfinder tends to do this for items that look similar, make sure that the steel bars are at the top of your bank

**Comment by ineedbots** [comment]
Also make sure that your `MATERIAL_RATIO` and `SECONDARY_MATERIAL_RATIO` are set correctly, in this case they should both be set to 1

**Comment by heebybeeby** [comment]
Yepp I had done that as well. I could provide my config if you'd like.

**Comment by ineedbots** [comment]
everything works fine for me, just tested never encountered your issues.
